import LocalizedStrings from "react-localization";

let strings =new LocalizedStrings({
    en:{
        trackYourShipment:'Track your shipment',
        DeliveryDateIsOver:'Delivery time within',
        nameOfMerchant:'name of merchant',
        lastUpdate:'last update',
        shipmentNumber:'shipment number',
        shipmentDetails:'Shipment details',
        theBranch:'The branch',
        history:'History',
        time:'Time',
        details:'Details',
        ticketCreated:'The shipment was created',
        packageReceived:'Package Received',
        orderTransferredToHub:'Order is being transferred to bosta Hub',
        outForDelivery:'Out For Delivery',
        shipmentNotDelivered:'The shipment was not delivered',
        notYetShipped:'Not Yet Shipped',
        deliverdToSender:'DELIVERED TO SENDER',
        cancelled:'Cancelled',
        delivered:'Delivered',
        reasonCustomerNotInAddress:'Retry delivery - the customer is not in the address',
        reasonCustomerRequestedForAnotherDay:'Postponed - the customer requested postponement for another day',
        reasonCustomerNotAnswering:'Customer is not answering',
        deliveryAddress:'Delivery address',
        problemYourShipment:'Is there a problem with your shipment?',
        reportProblem:'Report a problem',
        trackingNum:'Tracking Num',
        home:'Home',
        prices:'Prices',
        callSales:'Call sales'
    },
    ar:{
        trackYourShipment:'تتبع شحنتك',
        DeliveryDateIsOver:'موعد التسليم خلال',
        nameOfMerchant:'اسم التاجر',
        lastUpdate:'اخر تحديث',
        shipmentNumber:'رقم الشحنة',
        shipmentDetails:'تفاصيل الشحنة',
        theBranch:'الفرع',
        history:'التاريخ',
        time:'الوقت',
        details:'تفاصيل',
        ticketCreated:'تم انشاء الشحنة',
        packageReceived:'تم استلام الشحنة',
        orderTransferredToHub:'يتم نقل الطلب إلى مركز بوستا',
        outForDelivery:'الشحنة خرجت للتسليم',
        shipmentNotDelivered:'لم يتم تسليم الشحنة',
        notYetShipped:'لم يتم شحنها بعد',
        deliverdToSender:'سلمت للبائع',
        cancelled:'تم الغاء الشحنة',
        delivered:'تم التسليم',
        reasonCustomerNotInAddress:'إعادة التسليم - العميل ليس في العنوان',
        reasonCustomerRequestedForAnotherDay:'مؤجل - طلب العميل التأجيل ليوم آخر',
        reasonCustomerNotAnswering:'العميل لا يجيب',
        deliveryAddress:'عنوان التسليم',
        problemYourShipment:'هل يوجد مشكلة فى شحنتك',
        reportProblem:'ابلاغ عن مشكلة',
        trackingNum:'رقم التتبع',
        home:'الرئيسية',
        prices:'الأسعار',
        callSales:'كلم المبيعات'
    }
})
export default strings